# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/egouletlang/EthosSpecs.git'

target 'EthosImage' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'EthosUtil'
  pod 'EthosNetwork'

  # Pods for EthosImage

  target 'EthosImageTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'EthosUtil'
	pod 'EthosNetwork'
  end

end
