# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/egouletlang/EthosSpecs.git'

target 'SampleApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'EthosUtil'
  pod 'EthosImage'
  pod 'EthosText'
  pod 'EthosUI'

  # Pods for SampleApp

  target 'SampleAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'EthosUtil'
    pod 'EthosImage'
    pod 'EthosText'
    pod 'EthosUI'
  end

  target 'SampleAppUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'EthosUtil'
    pod 'EthosImage'
    pod 'EthosText'
    pod 'EthosUI'
  end

end
