# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/egouletlang/EthosSpecs.git'

target 'EthosNetwork' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyJSON', '~> 4.3.0'
  pod 'Alamofire', '~> 4.8.2'
  pod 'EthosUtil'

  # Pods for EthosNetwork

  target 'EthosNetworkTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SwiftyJSON', '~> 4.3.0'
    pod 'Alamofire', '~> 4.8.2'
    pod 'EthosUtil'
  end

end
